### ISSUE TITLE
feature: shadow mode closed

### ISSUE THREAD

**Issue by Weedshaker** [justinfagnani/html-include-element#3]
Hi,

I think its very cool that we finally see people create web components! And you got me the idea to make fetch options through the attribute available. Thanks!

Although, it would be nice, if you could support shadow mode->closed to make this complete... I got something similar here: https://github.com/Weedshaker/web-components/blob/master/fetch/FetchContainer.js
Where I let the user choose the shadow mode... You basically just need to copy the html-tags children into the shadow to make mode closed work.

Cheers

**Comment by justinfagnani** [comment]
What's the use case? So-called "open" shadow roots are pretty closed, and so-called "closed" shadow roots really aren't any more closed. Someone can always patch `attachShadow` and get to them.

**Comment by Weedshaker** [comment]
Yes, hijacking the attachShadow... I completely agree. But I think its nice to implement it as close to the standard as possible.
https://blog.revillweb.com/open-vs-closed-shadow-dom-9f3d7427d1af

**Comment by justinfagnani** [comment]
I don't see a clear benefit here. If the user can choose the shadow mode, what are closed shadow roots protecting against?

**Comment by Weedshaker** [comment]
...the default shadowRoot access

**Comment by justinfagnani** [comment]
Sorry, I don't understand the actual difference here - I don't think closed shadow roots really change the operation of this element. They don't really protect against anything. I want to be conservative with the number of options, so without a clear description of what this would achieve, I'm going to close this for now. Thanks.
