### ISSUE TITLE
Light Content Blown away on Load

### ISSUE THREAD

**Issue by bennypowers** [justinfagnani/html-include-element#9]
https://github.com/justinfagnani/html-include-element/blob/8f5850744f7921e90b0332c6263685301411ae91/html-include-element.js#L128
This line blows away any slotted content on load.

It should be 

```js
      if (this.noShadow) this.innerHTML = text;
```

**Comment by bennypowers** [comment]
Why is this a problem?

From README.md:

-----

### Composition

Since the included HTML is rendered in a shadow root, it can contain `<slot>` elements, allowing the included content to project children from the `<html-include>` into itself. This may be a fringe case, but imaging a CMS system where the content can control where certain host-provided blocks go. I'm very curious to see how this might be used.

Main page:
```html
<html-include>
  <div slot="suggested-articles">...</div>
</html-include>
```

Content:
```html
<article>
  <header>...</header>
  <main>...</main>
  <!-- render suggested articles here -->
  <slot name="suggested-articles"></slot>
  <footer>...</footer>
</article>
```
-----
But this doesn't actually work, since the slotted contend that you added gets destroyed by the above line

**Comment by justinfagnani** [comment]
Good catch. Thanks!
